### ISSUE TITLE
Clicking "your pending reviews" ONLY takes you to canva repo pulls

### ISSUE THREAD

**Issue by josegalarza** [realyze/CanvaBoy#1]
When I right-click on CanvaBoy, and click in some of the "Your pending reviews", it takes me to `https://github.com/canva/canva/pulls?...`, although the PRs are in another repo (`data-warehouse`).
Maybe there's a way of foxing this, or even a configuration for the default repo per user would be good enough.

**Comment by realyze** [comment]
Ah, interesting, thanks for the report! Could you share which repo it is please and what is the full link it opens? You can DM me on slack (preferred so that we don't accidentally expose anything :) ).

**Comment by realyze** [comment]
Also, is that on Mac OS? Because the `/pulls?` should only open when you left-click the canvaboy icon, not when you click on the pending review.

**Comment by realyze** [comment]
Released in https://github.com/realyze/CanvaBoy/releases/tag/0.10.1 , thanks for the idea @josegalarza !
